<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="3" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-24T17:03:44 IST" name="Student Name Field Validation Suite" finished-at="2025-07-24T17:04:44 IST" duration-ms="60261">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-07-24T17:03:44 IST" name="Cucumber-TestNG Execution" finished-at="2025-07-24T17:04:44 IST" duration-ms="60261">
      <class name="runners.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:03:44 IST" name="setUpClass" finished-at="2025-07-24T17:03:45 IST" duration-ms="854" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1c7350b0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:03:45 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:03:57 IST" duration-ms="11638" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:03:57 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:05 IST" duration-ms="7969" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected message to start with: 'Minimum 2 characters required', but got: 'Registration was successful. The roll number generated is 4878.' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected message to start with: 'Minimum 2 characters required', but got: 'Registration was successful. The roll number generated is 4878.' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.RegistrationSteps.validate_dynamic_result(RegistrationSteps.java:76)
at ✽.the result should be "Minimum 2 characters required"(file:///C:/Users/Asus/OneDrive/Desktop/Cogni/sprint2/src/test/resources/features/registration.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:05 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:13 IST" duration-ms="7821" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:13 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:20 IST" duration-ms="7897" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected message to start with: 'No numbers allowed in student name', but got: 'Registration was successful. The roll number generated is 4880.' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected message to start with: 'No numbers allowed in student name', but got: 'Registration was successful. The roll number generated is 4880.' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.RegistrationSteps.validate_dynamic_result(RegistrationSteps.java:76)
at ✽.the result should be "No numbers allowed in student name"(file:///C:/Users/Asus/OneDrive/Desktop/Cogni/sprint2/src/test/resources/features/registration.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:20 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:28 IST" duration-ms="7880" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected message to start with: 'No special characters allowed', but got: 'Registration was successful. The roll number generated is 4881.' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected message to start with: 'No special characters allowed', but got: 'Registration was successful. The roll number generated is 4881.' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.RegistrationSteps.validate_dynamic_result(RegistrationSteps.java:76)
at ✽.the result should be "No special characters allowed"(file:///C:/Users/Asus/OneDrive/Desktop/Cogni/sprint2/src/test/resources/features/registration.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:28 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:36 IST" duration-ms="8103" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected message to start with: 'Maximum 30 characters allowed', but got: 'Registration was successful. The roll number generated is 4882.' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected message to start with: 'Maximum 30 characters allowed', but got: 'Registration was successful. The roll number generated is 4882.' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.RegistrationSteps.validate_dynamic_result(RegistrationSteps.java:76)
at ✽.the result should be "Maximum 30 characters allowed"(file:///C:/Users/Asus/OneDrive/Desktop/Cogni/sprint2/src/test/resources/features/registration.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:36 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-07-24T17:04:44 IST" duration-ms="7995" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Student Name field"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Student Name Field Validation"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:runners.TestRunner@3bb9a3ff]" started-at="2025-07-24T17:04:44 IST" name="tearDownClass" finished-at="2025-07-24T17:04:44 IST" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runners.TestRunner -->
    </test> <!-- Cucumber-TestNG Execution -->
  </suite> <!-- Student Name Field Validation Suite -->
</testng-results>
